import { defineConfig } from "@playwright/test";

/** Module, server-rendered component, and anonymous API tests only.
 * These do not launch a browser, require credentials, or mutate business records.
 * Keep browser/device acceptance in the default and live-persistence suites. */
export default defineConfig({
  testDir: "./e2e",
  testMatch: [
    "ai-homeworks-ownership.spec.ts",
    "ai-provider-recovery.spec.ts",
    "ai-request-control.spec.ts",
    "ai-source-context.spec.ts",
    "calendar-display-recovery.spec.ts",
    "ci-runtime.spec.ts",
    "collections-review.spec.ts",
    "homeworks-automatic.spec.ts",
    "homeworks-enrich.spec.ts",
    "homeworks-historical.spec.ts",
    "homeworks-linking.spec.ts",
    "homeworks-ownership-actions.spec.ts",
    "homeworks-reconcile-range.spec.ts",
    "homeworks-reconcile-week.spec.ts",
    "homeworks-schedule-completeness.spec.ts",
    "homeworks-status-safety.spec.ts",
    "homeworks-sync-failures.spec.ts",
    "homeworks-ui-recovery.spec.ts",
    "homeworks-webhook.spec.ts",
    "homeworks-write-safety.spec.ts",
    "integration-api-safety.spec.ts",
    "integration-owner-access.spec.ts",
    "integration-reliability.spec.ts",
    "jarvis-experience.spec.ts",
    "jarvis-memory.spec.ts",
    "job-not-found.spec.ts",
    "job-section-isolation.spec.ts",
    "mobile-viewport.spec.ts",
    "notes-tasks.spec.ts",
    "oauth-integrations.spec.ts",
    "oauth-public-pages.spec.ts",
    "oauth-state-safety.spec.ts",
    "oauth-ui-status.spec.ts",
    "owner-data-safety.spec.ts",
    "photo-intake.spec.ts",
    "quickbooks-diagnostics.spec.ts",
    "schedule-authority.spec.ts",
    "scheduling-and-revenue.spec.ts",
    "session-recovery.spec.ts",
    "workspace-health.spec.ts",
  ],
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  workers: 2,
  retries: 0,
  reporter: [["list"]],
  timeout: 60_000,
  use: { baseURL: "http://localhost:3126" },
  webServer: {
    command: "npm run dev -- --port 3126",
    url: "http://localhost:3126/login",
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
