import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy | Jarvis", description: "How Jarvis handles account, business, and Google Calendar information." };
const section = "space-y-3";
const heading = "text-xl font-semibold text-[var(--color-text-primary)]";

export default function PrivacyPage() {
  return (
    <article className="max-w-3xl space-y-8 text-base leading-7 text-[var(--color-text-secondary)]">
      <header className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-accent)]">Jarvis / Your data</p><h1 className="text-4xl font-semibold tracking-tight text-[var(--color-text-primary)]">Privacy Policy</h1><p className="text-sm">Effective October 10, 2026</p></header>
      <section className={section}><h2 className={heading}>Who operates Jarvis</h2><p>Jarvis is the private operations workspace operated by Nate Hall for WeedEater Lawn Care. This policy covers the Jarvis application and its connected services.</p></section>
      <section className={section}><h2 className={heading}>Information Jarvis uses</h2><p>Jarvis processes sign-in information, authorized business records, notes, tasks, and information supplied through its features. Business records may include customer contact information, property details, schedules, jobs, invoices, and payment records from connected systems. Access to each integration depends on the permissions granted to Jarvis.</p></section>
      <section className={section}><h2 className={heading}>Google Calendar access and use</h2><p>When the account owner connects Google Calendar, Jarvis requests the calendar.readonly permission. This allows it to list calendars the Google account can access and read events. The owner selects the calendar used for event previews and live connection checks.</p><p>Event information may include titles, dates, times, and other details returned by Google Calendar. Jarvis displays calendar previews separately from Homeworks jobs. It does not create, modify, or delete Google Calendar events or convert them into billable jobs.</p></section>
      <section className={section}><h2 className={heading}>Storage and retention</h2><p>Jarvis stores Google access and refresh tokens, authorization metadata, and the selected calendar identifier and name in its server-side Supabase database. These credentials support access without requiring a new sign-in for every read. Privileged credential access is restricted to the integration backend and authorized owner operations.</p><p>The current Calendar integration reads event previews on demand and does not save the returned event list as a separate set of business records in the database. Preview data is processed by the hosting service and displayed in the signed-in browser. Service providers may retain operational logs and backups according to their configured retention.</p></section>
      <section className={section}><h2 className={heading}>Service providers and sharing</h2><p>Jarvis uses Vercel for application hosting and Supabase for authentication and storage. Google processes Calendar authorization and API requests. These providers process information needed to deliver their services.</p><p>Jarvis AI may process questions and relevant business context through the configured AI provider. The current Calendar integration does not feed Calendar event previews or OAuth credentials into the AI assistant; it may report connection health. Information you deliberately include in a question is processed as part of that question.</p><p>Jarvis does not sell Google user data, use it for advertising, or use it to train general-purpose AI models. Any use or transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including its Limited Use requirements.</p></section>
      <section className={section}><h2 className={heading}>Disconnecting and deletion requests</h2><p>The owner can disconnect Google Calendar in Jarvis Settings. A successful disconnect removes the saved connection credentials and calendar selection from the active database and attempts to revoke the token with Google. Access can also be revoked directly in the Google account&apos;s third-party connections settings.</p><p>Disconnecting does not delete events in Google Calendar or business records in Homeworks or QuickBooks. Contact the operator for requests about other stored information or backup retention. Data needed for business recordkeeping may be handled separately from integration credentials.</p></section>
      <section className={section}><h2 className={heading}>Security and browser features</h2><p>Jarvis uses authenticated workspace access, server-side integration permissions, and HTTPS connections. No system can guarantee absolute security. Sign-in uses cookies. Conversation history and preferences may be saved in the browser; the interface provides controls for supported local history. Voice features use the browser&apos;s speech service when enabled.</p></section>
      <section className={section}><h2 className={heading}>Questions and updates</h2><p>For privacy questions or requests, contact <a className="break-all text-[var(--color-accent)] underline underline-offset-4" href="mailto:natehall9876@gmail.com">natehall9876@gmail.com</a>. This policy will be updated when the application&apos;s data practices change.</p><p><Link href="/about" className="text-[var(--color-accent)] underline underline-offset-4">About Jarvis</Link></p></section>
    </article>
  );
}
